<?php
use App\Core\Csrf;
$customer=$invoice['company_name']?:$invoice['contact_name'];
$address=array_filter([$invoice['address_line_1'],$invoice['address_line_2'],$invoice['town_city'],$invoice['county'],$invoice['postcode']]);
$canManage=!empty($canManage);
?>
<header class="page-header invoice-page-header">
 <div><a class="back-link" href="<?= $canManage?'/invoices':'/portal/invoices' ?>">← <?= $canManage?'Invoices':'My Invoices' ?></a><div class="eyebrow">Invoice details</div><h1><?= htmlspecialchars((string)$invoice['invoice_number']) ?></h1><p><?= htmlspecialchars((string)$customer) ?> · Due <?= date('j F Y',strtotime((string)$invoice['due_date'])) ?></p></div>
 <div class="header-actions no-print"><?php if($canManage&&in_array($invoice['status'],['draft','sent','overdue','partially_paid'],true)&&$invoice['amount_paid']==0): ?><a class="secondary-button" href="/invoices/<?= (int)$invoice['id'] ?>/edit">Edit</a><?php endif; ?><button class="secondary-button" onclick="window.print()">Print invoice</button><span class="status <?= htmlspecialchars((string)$invoice['status']) ?>"><?= htmlspecialchars(ucwords(str_replace('_',' ',(string)$invoice['status']))) ?></span></div>
</header>
<?php if($flash): ?><div class="alert <?= htmlspecialchars($flash['type']) ?> no-print"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
<article class="invoice-document">
 <header><div class="invoice-brand"><span class="brand-mark">V</span><div><strong>Veelox Digital</strong><small>Invoice</small></div></div><div class="invoice-number"><small>Invoice number</small><strong><?= htmlspecialchars((string)$invoice['invoice_number']) ?></strong></div></header>
 <section class="invoice-parties"><div><small>Bill to</small><strong><?= htmlspecialchars((string)$customer) ?></strong><span><?= htmlspecialchars((string)$invoice['contact_name']) ?><br><?= implode('<br>',array_map('htmlspecialchars',$address)) ?><br><?= htmlspecialchars((string)$invoice['email']) ?></span></div><dl><div><dt>Issue date</dt><dd><?= date('j F Y',strtotime((string)$invoice['issue_date'])) ?></dd></div><div><dt>Due date</dt><dd><?= date('j F Y',strtotime((string)$invoice['due_date'])) ?></dd></div><?php if($invoice['order_number']): ?><div><dt>Order</dt><dd><?= htmlspecialchars((string)$invoice['order_number']) ?></dd></div><?php endif; ?></dl></section>
 <div class="invoice-lines"><div class="line-head"><span>Description</span><span>Quantity</span><span>Unit price</span><span>Total</span></div><?php foreach($items as $item): ?><div class="line-row"><strong><?= htmlspecialchars((string)$item['description']) ?></strong><span><?= rtrim(rtrim(number_format((float)$item['quantity'],2),'0'),'.') ?></span><span>£<?= number_format($item['unit_price_amount']/100,2) ?></span><span>£<?= number_format($item['line_total_amount']/100,2) ?></span></div><?php endforeach; ?></div>
 <section class="invoice-bottom"><div><?php if($invoice['notes']): ?><small>Notes</small><p><?= nl2br(htmlspecialchars((string)$invoice['notes'])) ?></p><?php endif; ?><?php if($bank['sort_code']||$bank['account_number']): ?><small>Bank transfer details</small><p><?= htmlspecialchars((string)$bank['account_name']) ?><br><?= htmlspecialchars((string)$bank['name']) ?><br>Sort code: <?= htmlspecialchars((string)$bank['sort_code']) ?><br>Account: <?= htmlspecialchars((string)$bank['account_number']) ?><br>Reference: <?= htmlspecialchars((string)$invoice['invoice_number']) ?></p><?php endif; ?></div><dl class="invoice-totals"><div><dt>Subtotal</dt><dd>£<?= number_format($invoice['subtotal_amount']/100,2) ?></dd></div><div><dt>Paid</dt><dd>£<?= number_format($invoice['amount_paid']/100,2) ?></dd></div><div class="balance"><dt>Balance due</dt><dd>£<?= number_format($invoice['balance_due']/100,2) ?></dd></div></dl></section>
</article>
<?php if(!$canManage&&$stripeEnabled&&$invoice['balance_due']>0&&!in_array($invoice['status'],['draft','void','refunded'],true)): ?><section class="portal-payment no-print"><div><span class="eyebrow">Secure card payment</span><h2>Pay £<?= number_format($invoice['balance_due']/100,2) ?> online</h2><p>You’ll be transferred to Stripe’s secure checkout to complete your payment.</p></div><form method="post" action="/portal/invoices/<?= (int)$invoice['id'] ?>/stripe-checkout"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><button class="stripe-button" type="submit">Pay securely by card →</button></form></section><?php endif; ?>
<?php if($canManage): ?>
<div class="invoice-management no-print">
 <section class="detail-card"><div class="panel-heading"><div><span class="eyebrow">Payments</span><h2>Payment history</h2></div></div><?php if(!$payments): ?><p class="muted">No payments have been recorded.</p><?php else: ?><div class="payment-list"><?php foreach($payments as $payment): ?><div><span class="metric-icon green">£</span><span><strong>£<?= number_format($payment['amount']/100,2) ?></strong><small><?= date('j M Y, g:i a',strtotime((string)$payment['paid_at'])) ?> · <?= htmlspecialchars((string)($payment['payment_reference']?:'No reference')) ?></small></span><span class="status paid">Paid</span></div><?php endforeach; ?></div><?php endif; ?></section>
 <aside><?php if($invoice['balance_due']>0&&!in_array($invoice['status'],['void','refunded'],true)): ?><section class="detail-card"><div class="panel-heading"><div><span class="eyebrow">Bank transfer</span><h2>Record payment</h2></div></div><form class="payment-form" method="post" action="/invoices/<?= (int)$invoice['id'] ?>/payments"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><label>Amount (£)<input name="amount" inputmode="decimal" value="<?= number_format($invoice['balance_due']/100,2,'.','') ?>" required></label><label>Payment date<input type="date" name="paid_at" value="<?= date('Y-m-d') ?>" required></label><label>Bank reference<input name="reference" maxlength="190" placeholder="Transaction reference"></label><button class="primary-button full" type="submit">Record bank payment</button></form></section><?php endif; ?><?php if($invoice['amount_paid']==0): ?><section class="detail-card"><div class="panel-heading"><div><span class="eyebrow">Status</span><h2>Invoice workflow</h2></div></div><form method="post" action="/invoices/<?= (int)$invoice['id'] ?>/status"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><label class="status-select">Change status<select name="status"><option value="draft" <?= $invoice['status']==='draft'?'selected':'' ?>>Draft</option><option value="sent" <?= in_array($invoice['status'],['sent','overdue'],true)?'selected':'' ?>>Sent / outstanding</option><option value="void" <?= $invoice['status']==='void'?'selected':'' ?>>Void</option></select></label><button class="secondary-button full" type="submit">Update invoice</button></form></section><?php endif; ?></aside>
</div>
<?php endif; ?>
