<?php

use App\Core\Csrf;

$billingLabel = $package['billing_type'] === 'one_off' ? 'One-off payment' : ucfirst((string) $package['billing_interval']) . ' recurring';
?>
<header class="page-header package-header"><div><a class="back-link" href="/packages">← Plans &amp; Packages</a><div class="profile-title"><span class="profile-avatar package-avatar">▦</span><div><div class="eyebrow"><?= htmlspecialchars((string) $package['slug']) ?></div><h1><?= htmlspecialchars((string) $package['name']) ?></h1><p><?= htmlspecialchars($billingLabel) ?> · <?= $package['is_public'] ? 'Public package' : 'Internal package' ?></p></div></div></div><div class="header-actions"><?php if($package['status']==='active'): ?><a class="primary-button" href="/orders/create?package=<?= (int)$package['id'] ?>">Use package</a><?php endif; ?><a class="secondary-button" href="/packages/<?= (int) $package['id'] ?>/edit">Edit package</a><span class="status <?= htmlspecialchars((string) $package['status']) ?>"><?= htmlspecialchars(ucfirst((string) $package['status'])) ?></span></div></header>
<?php if ($flash): ?><div class="alert <?= htmlspecialchars($flash['type']) ?>"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
<section class="mini-metrics"><article><small>Package price</small><strong>£<?= number_format($package['price_amount']/100,2) ?></strong></article><article><small>Active orders</small><strong><?= number_format((int)($metrics['active_count']??0)) ?></strong></article><article><small>Customers</small><strong><?= number_format((int)($metrics['customer_count']??0)) ?></strong></article><article><small>Total revenue</small><strong>£<?= number_format(($metrics['revenue_amount']??0)/100,2) ?></strong></article></section>
<div class="profile-grid package-profile"><div class="profile-main">
    <section class="detail-card"><div class="panel-heading"><div><span class="eyebrow">Overview</span><h2>Package description</h2></div></div><div class="package-description"><?= $package['description'] ? nl2br(htmlspecialchars((string)$package['description'])) : '<span class="muted">No description has been added.</span>' ?></div></section>
    <section class="detail-card"><div class="panel-heading"><div><span class="eyebrow">Deliverables</span><h2>Included features</h2></div></div><?php if ($features): ?><ul class="feature-list"><?php foreach ($features as $feature): ?><li><span>✓</span><?= htmlspecialchars((string)$feature) ?></li><?php endforeach; ?></ul><?php else: ?><p class="muted">No included features have been added.</p><?php endif; ?></section>
</div><aside class="profile-side">
    <section class="detail-card"><div class="panel-heading"><div><span class="eyebrow">Billing</span><h2>Pricing summary</h2></div></div><dl class="summary-list"><div><dt>Base price</dt><dd>£<?= number_format($package['price_amount']/100,2) ?></dd></div><div><dt>Billing</dt><dd><?= htmlspecialchars($billingLabel) ?></dd></div><div><dt>Setup fee</dt><dd>£<?= number_format($package['setup_fee_amount']/100,2) ?></dd></div><div><dt>Visibility</dt><dd><?= $package['is_public'] ? 'Public' : 'Internal only' ?></dd></div></dl></section>
    <section class="detail-card"><div class="panel-heading"><div><span class="eyebrow">Actions</span><h2>Package tools</h2></div></div><form method="post" action="/packages/<?= (int)$package['id'] ?>/duplicate"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><button class="secondary-button full" type="submit">Duplicate package</button></form><?php if ($package['status']!=='archived'): ?><form class="archive-form" method="post" action="/packages/<?= (int)$package['id'] ?>/archive" onsubmit="return confirm('Archive this package? Existing orders will remain unchanged.')"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>"><button class="danger-button full" type="submit">Archive package</button></form><?php endif; ?></section>
</aside></div>
