<?php use App\Core\Csrf; $editing=!empty($order['id']); ?>
<?php if($errors): ?><div class="alert error"><?= implode('<br>',array_map(static fn($error)=>htmlspecialchars((string)$error),$errors)) ?></div><?php endif; ?>
<form class="record-form order-form" action="<?= $editing?'/orders/'.(int)$order['id']:'/orders' ?>" method="post"><input type="hidden" name="_token" value="<?= htmlspecialchars(Csrf::token()) ?>">
<section class="form-card"><div class="form-heading"><span>01</span><div><h2>Customer and service</h2><p>Choose who the order belongs to and the package being supplied.</p></div></div><div class="form-grid">
<label>Customer *<select name="customer_id" required><option value="">Select a customer</option><?php foreach($customers as $customer): ?><option value="<?= (int)$customer['id'] ?>" <?= (int)($order['customer_id']??0)===(int)$customer['id']?'selected':'' ?>><?= htmlspecialchars((string)($customer['company_name']?:$customer['contact_name'])) ?> · <?= htmlspecialchars((string)$customer['account_number']) ?></option><?php endforeach; ?></select></label>
<label>Package<select id="package-select" name="package_id"><option value="">Custom service</option><?php foreach($packages as $package): ?><option value="<?= (int)$package['id'] ?>" data-name="<?= htmlspecialchars((string)$package['name']) ?>" data-price="<?= number_format($package['price_amount']/100,2,'.','') ?>" data-setup="<?= number_format($package['setup_fee_amount']/100,2,'.','') ?>" data-type="<?= htmlspecialchars((string)$package['billing_type']) ?>" data-interval="<?= htmlspecialchars((string)$package['billing_interval']) ?>" <?= (int)($order['package_id']??0)===(int)$package['id']?'selected':'' ?>><?= htmlspecialchars((string)$package['name']) ?><?= $package['status']!=='active'?' ('.htmlspecialchars((string)$package['status']).')':'' ?></option><?php endforeach; ?></select></label>
<label class="wide">Order description *<input id="description" name="description" maxlength="255" value="<?= htmlspecialchars((string)($order['description']??'')) ?>" placeholder="e.g. Five-page business website" required></label>
</div></section>
<section class="form-card"><div class="form-heading"><span>02</span><div><h2>Pricing and billing</h2><p>Package prices are filled automatically but can be customised for this order.</p></div></div><div class="form-grid">
<label>Billing type<select id="billing-type" name="billing_type"><option value="one_off" <?= ($order['billing_type']??'')==='one_off'?'selected':'' ?>>One-off payment</option><option value="recurring" <?= ($order['billing_type']??'')==='recurring'?'selected':'' ?>>Recurring payment</option></select></label>
<label id="billing-interval">Billing interval<select name="billing_interval"><option value="monthly" <?= ($order['billing_interval']??'')==='monthly'?'selected':'' ?>>Monthly</option><option value="yearly" <?= ($order['billing_interval']??'')==='yearly'?'selected':'' ?>>Yearly</option></select></label>
<label>Service price (£) *<input id="price" inputmode="decimal" name="price" value="<?= htmlspecialchars((string)($order['price']??'')) ?>" placeholder="0.00" required></label><label>Setup fee (£)<input id="setup-fee" inputmode="decimal" name="setup_fee" value="<?= htmlspecialchars((string)($order['setup_fee']??'0.00')) ?>" placeholder="0.00"></label>
<label>Start date<input type="date" name="starts_at" value="<?= htmlspecialchars((string)($order['starts_at']??'')) ?>"></label><label id="renewal-date">Next renewal date<input type="date" name="renews_at" value="<?= htmlspecialchars((string)($order['renews_at']??'')) ?>"></label>
</div></section>
<section class="form-card"><div class="form-heading"><span>03</span><div><h2>Workflow</h2><p>Set ownership, current status and private staff notes.</p></div></div><div class="form-grid"><label>Assigned staff<select name="assigned_to"><option value="">Unassigned</option><?php foreach($staff as $member): ?><option value="<?= (int)$member['id'] ?>" <?= (int)($order['assigned_to']??0)===(int)$member['id']?'selected':'' ?>><?= htmlspecialchars((string)$member['name']) ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><?php foreach(['draft','pending','awaiting_payment','paid','active','completed','cancelled','refunded'] as $value): ?><option value="<?= $value ?>" <?= ($order['status']??'')===$value?'selected':'' ?>><?= htmlspecialchars(ucwords(str_replace('_',' ',$value))) ?></option><?php endforeach; ?></select></label><label class="wide">Internal notes<textarea name="internal_notes" rows="5" placeholder="Private notes visible only to Veelox staff..."><?= htmlspecialchars((string)($order['internal_notes']??'')) ?></textarea></label></div></section>
<div class="form-actions"><a class="secondary-button" href="<?= $editing?'/orders/'.(int)$order['id']:'/orders' ?>">Cancel</a><button class="primary-button" type="submit"><?= $editing?'Save changes':'Create order' ?></button></div></form>
<script>
const packageSelect=document.getElementById('package-select'),billingType=document.getElementById('billing-type'),interval=document.getElementById('billing-interval'),renewal=document.getElementById('renewal-date');
function billingVisibility(){const recurring=billingType.value==='recurring';interval.hidden=!recurring;renewal.hidden=!recurring}billingType.addEventListener('change',billingVisibility);billingVisibility();
packageSelect.addEventListener('change',()=>{const option=packageSelect.selectedOptions[0];if(!option||!option.value)return;document.getElementById('description').value=option.dataset.name;document.getElementById('price').value=option.dataset.price;document.getElementById('setup-fee').value=option.dataset.setup;billingType.value=option.dataset.type;interval.querySelector('select').value=option.dataset.interval==='yearly'?'yearly':'monthly';billingVisibility()});
</script>
