<header class="page-header"><div><div class="eyebrow">Sales</div><h1>Customer Orders</h1><p>Manage one-off projects and recurring customer services.</p></div><a class="primary-button" href="/orders/create">+ Create order</a></header>
<?php if ($flash): ?><div class="alert <?= htmlspecialchars($flash['type']) ?>"><?= htmlspecialchars($flash['message']) ?></div><?php endif; ?>
<section class="list-panel">
    <form class="toolbar order-toolbar" method="get" action="/orders">
        <div class="search-box"><span>⌕</span><input name="search" value="<?= htmlspecialchars($search) ?>" placeholder="Search number, customer or service..."></div>
        <select name="status" onchange="this.form.submit()"><option value="">All statuses</option><?php foreach (['draft','pending','awaiting_payment','paid','active','completed','cancelled','refunded'] as $value): ?><option value="<?= $value ?>" <?= $status===$value?'selected':'' ?>><?= htmlspecialchars(ucwords(str_replace('_',' ',$value))) ?></option><?php endforeach; ?></select>
        <select name="billing" onchange="this.form.submit()"><option value="">All billing</option><option value="one_off" <?= $billing==='one_off'?'selected':'' ?>>One-off</option><option value="monthly" <?= $billing==='monthly'?'selected':'' ?>>Monthly</option><option value="yearly" <?= $billing==='yearly'?'selected':'' ?>>Yearly</option></select>
        <button class="secondary-button" type="submit">Search</button>
    </form>
    <?php if ($orders===[]): ?><div class="empty-state tall"><span>◇</span><h3>No orders found</h3><p>Create an order or change your search filters.</p><a class="primary-button" href="/orders/create">Create an order</a></div><?php else: ?><div class="table-wrap"><table class="data-table order-table"><thead><tr><th>Order</th><th>Customer</th><th>Billing</th><th>Total</th><th>Assigned to</th><th>Status</th><th></th></tr></thead><tbody>
    <?php foreach($orders as $item): $customer=$item['company_name']?:$item['contact_name']; $billingLabel=$item['billing_type']==='one_off'?'One-off':ucfirst((string)$item['billing_interval']); ?><tr><td><a class="order-reference" href="/orders/<?= (int)$item['id'] ?>"><strong><?= htmlspecialchars((string)$item['order_number']) ?></strong><small><?= htmlspecialchars((string)$item['description']) ?></small></a></td><td><strong><?= htmlspecialchars((string)$customer) ?></strong><small class="table-subline"><?= htmlspecialchars((string)$item['account_number']) ?></small></td><td><?= htmlspecialchars($billingLabel) ?></td><td><strong>£<?= number_format($item['total_amount']/100,2) ?></strong></td><td><?= htmlspecialchars((string)($item['assignee_name']?:'Unassigned')) ?></td><td><span class="status <?= htmlspecialchars((string)$item['status']) ?>"><?= htmlspecialchars(ucwords(str_replace('_',' ',(string)$item['status']))) ?></span></td><td><a class="row-action" href="/orders/<?= (int)$item['id'] ?>">View ›</a></td></tr><?php endforeach; ?>
    </tbody></table></div><?php endif; ?>
</section>
